name: SellManager
main: SellManager\Main
version: 1.0.0
api: 5.0.0
author: ZyberPE
depend: [EconomyAPI]

commands:
  sellhand:
    description: Sell the item in your hand
    usage: "/sellhand"
    permission: sellmanager.command.sellhand

  sellall:
    description: Sell all sellable items in your inventory
    usage: "/sellall"
    permission: sellmanager.command.sellall

  blockprices:
    description: Show sell prices
    usage: "/blockprices"
    permission: sellmanager.command.blockprices

permissions:
  sellmanager.command.sellhand:
    default: true

  sellmanager.command.sellall:
    default: true

  sellmanager.command.blockprices:
    default: true

  sell.rank:
    default: op
