name: SellManager
main: SellManager\Main
version: 1.0.0
api: 5.0.0
author: ZyberPE
depend: [EconomyAPI]

commands:
  sellhand:
    description: Sell the item in your hand
    usage: "/sellhand"
    permission: sellmanager.sellhand

  sellall:
    description: Sell all sellable items in inventory
    usage: "/sellall"
    permission: sellmanager.sellall

  blockprice:
    description: Show sell price of item in hand
    usage: "/blockprice"
    aliases: [bp]
    permission: sellmanager.blockprice

permissions:
  sellmanager.sellhand:
    default: op

  sellmanager.sellall:
    default: op

  sellmanager.blockprice:
    default: op

  sell.rank:
    default: op
